jobs:
  main:
    name: Test
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Download Packages
        run: sudo apt-get update && sudo apt-get install -y libhwloc15 unrar
      - name: Check
        run: ./test/run

name: Workflow

on:
  schedule:
    - cron: "50 1/3 * * *"
